### ISSUE TITLE
Explanation of cluster output file please

### ISSUE THREAD

**Issue by ckeeling** [bioCompU/Compacta#2]
Hello @bioCompU,

Could you explain each column of the cluster output file please, especially columns 3 and 4? Columns 1 and 2 are obvious, and I think columns 5 and 6 are contig length and coverage, respectively.

Column 3 contains 0 or 1.
Column 4 contains NC (cluster member from clustering?), SC (singlet from clustering?), SL (low read coverage?), and ZE (zero read coverage?).

For my data,
All SL contain a 1 in column 3.
All ZE contain a 1 in column 3.
Most, but not all of the SC contain a 1 in column 3.
If NC, only the representative contig in each cluster has a 1 in column 3, the rest are 0.

So, for a final filtered, non-redundant set, would you take only those sequences where NC=1 and SC=1?  What is the difference between SC=1 and SC=0?

Thanks,
Chris

**Comment by bioCompU** [comment]
Hi Chris!, 

As you mentioned the _clusters.txt  file contains 5 columns:
-columns 1 & 2 indicate the relation between a cluster and a contig.
-column 3 indicates whether the contig is representative of its cluster (marked with 1) or not (marked with 0).
-column 4 shows the status of each contig: 
    ZE (Zero evidence) when the contig has no reads mapping to it.  
    SC (Singleton contig) when the contig doesnt share reads with another contig.
    SL (Singleton by Low Evidence) contigs with few reads that were disconnected from others because of its reduced evidence.
    NC Contigs clustered with at least another contig.
-column 5 indicates the length of the contig.
-column 6 shows the number of reads mapped to the contig.

Are you sure you got some SC contigs with a 0 in the third column?, Singletons should be marked always as representatives of its own cluster (as they are all alone in its cluster).

To get a non-redundant set i would remove only those marked as ZE and NC=0, optionally you could also remove contigs marked as SL but it depends on your experiment.

Please let me know if you got SC=0 and if you would show me some of your output, i need to check if it is a bug to fix it.

Thanks!

**Comment by ckeeling** [comment]
Hello @bioCompU,

Thanks. I am definitely getting SC=0 for some.  Here is a matrix with different _d_ values:

```bash
	0	0.1	0.2	0.3	0.4	0.5	0.6	1.00
NC (1)	22183	32283	36154	38652	40274	41452	41847	12912
NC (0)	273626	259750	251977	245925	240693	235492	229992	47790
SC (1)	17239	20900	24721	28185	31694	35543	40303	180999
SC (0)	0	115	196	286	387	561	906	71347
SL (1)	420788	420788	420788	420788	420788	420788	420788	420788
ZE (1)	170	170	170	170	170	170	170	170
```

And here are some sections of the _d_=0.3 clusters file:
```bash
...
k64.S8483204	Cluster.460195	0	SC	369	21
k80.S3757478	Cluster.460195	1	SC	557	31
k64.S8919068	Cluster.460200	0	SC	536	28
k80.R8450791	Cluster.460200	1	SC	636	36
k64.S9058426	Cluster.460203	0	SC	810	49
k80.R8202410	Cluster.460203	1	SC	1526	846
k64.S9960088	Cluster.460223	0	SC	319	18
k80.S7918012	Cluster.460223	1	SC	395	31
...
k96.R5915206	Cluster.459326	0	SC	699	77
k96.R5933376	Cluster.459326	0	SC	472	43
k80.R8245570	Cluster.459326	1	SC	796	102
...
k64.R11270510	Cluster.459792	1	SC	570	31
k64.R11338338	Cluster.459792	0	SC	301	15
k64.R11406296	Cluster.459792	0	SC	391	20
...
```

Thanks for taking a look.
Chris

**Comment by bioCompU** [comment]
Hi Chris!,

I finally found what was causing the weird behavior, it was caused by some modifications we had to expand the output to provide more information in case the user needed it. Unfortunately, one of the functions was not recognizing some cases of Single contigs and treated them as if they were clustered (that`s why there were some SC =0).
I already updated the changes in the master code and updated the linux tarball, please let me know how it works.

Thank you!!

**Comment by ckeeling** [comment]
Thanks @bioCompU 

That looks like it did the trick (with a slightly different dataset):
```bash
	d=0.3 l=4.75
	before	after
NC (1)	37986	37986
NC (0)	256979	256979
SC (1)	28926	29343
SC (0)	417	0
SL	409588	409588
ZE	110	110
```

Cheers,
Chris
